export const JWT_SEC="qwertyrioup"
export const JWT_SECRET_KEY = "qwertyrioup"
export const CLINT_NODEMAILER_USER = "info@gentauronline.com"
export const CLINT_NODEMAILER_PASS = "dCJURmJpamJpaAT1"
export const MAIL_RECEIVERS = "us@genprice.com lieven@gentaur.com team@gentaur.com majri@gentaur.com ahmed@gentaur.com info@gentauronline.com qwertyrioup@gmail.com"
export const MONGODB_URI = "mongodb://GOKU:TomorrowLand4Ever%3B@168.119.197.134:27017/XYZ?authSource=XYZ"
export const ELASTIC_URL = "https://101-sv4.gentauronline.com"
export const ELASTIC_USERNAME = "elastic"
export const ELASTIC_PASSWORD = "Ha333Vhdr3qaz@"
